### ISSUE TITLE
not able to compile

### ISSUE THREAD

**Issue by kkberg** [tronxy3d/Gemini#1]
compiling ends with an error. Seems to something with the binaries which are included!

![Screenshot 2023-02-23 101737](https://user-images.githubusercontent.com/1121884/220866163-45f63778-cf4d-4518-8454-b5493f596fea.jpg)

**Comment by tronxy3d** [comment]
Please refer to FAQ to solve this problem

**Comment by kkberg** [comment]
I edited interrupt.cpp and excluded the double function.

**Comment by tronxy3d** [comment]
Is it the same problem

**Comment by kkberg** [comment]
Yes, problem as stated in faq. It is solved. Sadely the probided binaries are not in the level of this Marlin version. Please make sure you are providing firmware which is equal to the repisitory.
